import type { DbusNotification } from "./types"

export const mockNotifications: DbusNotification[] = [
  {
    id: 1,
    app_name: "Firefox",
    replaces_id: 0,
    app_icon: "web-browser",
    summary: "Download Complete",
    body: "linux-6.7.tar.gz has finished downloading",
    actions: ["default", "Open", "dismiss", "Dismiss"],
    hints: { category: "transfer.complete" },
    expire_timeout: 5000,
    urgency: 1,
    timestamp: new Date(Date.now() - 1000 * 60 * 5), // 5 minutes ago
    host: "workstation-01",
  },
  {
    id: 2,
    app_name: "System",
    replaces_id: 0,
    app_icon: "dialog-warning",
    summary: "Low Disk Space",
    body: 'The volume "Home" has only 2.3 GB disk space remaining',
    actions: [],
    hints: { urgency: 2, category: "device" },
    expire_timeout: 0,
    urgency: 2,
    timestamp: new Date(Date.now() - 1000 * 60 * 2), // 2 minutes ago
    host: "workstation-01",
  },
  {
    id: 3,
    app_name: "Thunderbird",
    replaces_id: 0,
    app_icon: "mail-unread",
    summary: "New Email",
    body: "You have 3 new messages from john@example.com",
    actions: ["default", "Open", "mark-read", "Mark as Read"],
    hints: { category: "email.arrived" },
    expire_timeout: 10000,
    urgency: 1,
    timestamp: new Date(Date.now() - 1000 * 60 * 15), // 15 minutes ago
    host: "laptop-dev",
  },
  {
    id: 4,
    app_name: "Update Manager",
    replaces_id: 0,
    app_icon: "system-software-update",
    summary: "Updates Available",
    body: "24 security updates are available for your system",
    actions: ["default", "Install", "later", "Remind Me Later"],
    hints: { category: "device", urgency: 1 },
    expire_timeout: -1,
    urgency: 1,
    timestamp: new Date(Date.now() - 1000 * 60 * 60), // 1 hour ago
    host: "server-prod",
  },
  {
    id: 5,
    app_name: "Spotify",
    replaces_id: 4,
    app_icon: "multimedia-player",
    summary: "Now Playing",
    body: "The Less I Know The Better - Tame Impala",
    actions: ["previous", "Previous", "next", "Next"],
    hints: { category: "x-gnome.music" },
    expire_timeout: 5000,
    urgency: 0,
    timestamp: new Date(Date.now() - 1000 * 30), // 30 seconds ago
    host: "laptop-dev",
  },
  {
    id: 6,
    app_name: "NetworkManager",
    replaces_id: 0,
    app_icon: "network-wireless",
    summary: "Connection Established",
    body: 'Connected to "Office WiFi 5GHz"',
    actions: [],
    hints: { category: "network.connected" },
    expire_timeout: 3000,
    urgency: 0,
    timestamp: new Date(Date.now() - 1000 * 60 * 120), // 2 hours ago
    host: "workstation-01",
  },
  {
    id: 7,
    app_name: "VS Code",
    replaces_id: 0,
    app_icon: "text-editor",
    summary: "Extension Update",
    body: "ESLint extension has been updated to version 2.4.0",
    actions: ["default", "View Changes"],
    hints: { category: "device.added" },
    expire_timeout: 8000,
    urgency: 0,
    timestamp: new Date(Date.now() - 1000 * 60 * 45), // 45 minutes ago
    host: "laptop-dev",
  },
  {
    id: 8,
    app_name: "Slack",
    replaces_id: 0,
    app_icon: "chat",
    summary: "Message from Engineering",
    body: "@sarah: Can you review the PR when you get a chance?",
    actions: ["default", "Open", "reply", "Reply"],
    hints: { category: "im.received" },
    expire_timeout: 10000,
    urgency: 1,
    timestamp: new Date(Date.now() - 1000 * 60 * 8), // 8 minutes ago
    host: "workstation-01",
  },
  {
    id: 9,
    app_name: "System",
    replaces_id: 0,
    app_icon: "battery-caution",
    summary: "Battery Low",
    body: "Battery is at 15%. Connect to a power source soon.",
    actions: [],
    hints: { urgency: 2, category: "device" },
    expire_timeout: 0,
    urgency: 2,
    timestamp: new Date(Date.now() - 1000 * 60 * 10), // 10 minutes ago
    host: "laptop-dev",
  },
  {
    id: 10,
    app_name: "Docker",
    replaces_id: 0,
    app_icon: "application-container",
    summary: "Container Started",
    body: "postgres_db container is now running on port 5432",
    actions: ["default", "View Logs"],
    hints: { category: "device" },
    expire_timeout: 5000,
    urgency: 0,
    timestamp: new Date(Date.now() - 1000 * 60 * 90), // 1.5 hours ago
    host: "server-prod",
  },
  {
    id: 11,
    app_name: "Calendar",
    replaces_id: 0,
    app_icon: "appointment-soon",
    summary: "Meeting Reminder",
    body: "Team standup starts in 15 minutes",
    actions: ["default", "Join", "snooze", "Snooze"],
    hints: { category: "x-gnome.alarm", urgency: 1 },
    expire_timeout: -1,
    urgency: 1,
    timestamp: new Date(Date.now() - 1000 * 60 * 3), // 3 minutes ago
    host: "workstation-01",
  },
  {
    id: 12,
    app_name: "Backup Service",
    replaces_id: 0,
    app_icon: "drive-harddisk",
    summary: "Backup Complete",
    body: "Successfully backed up 42.5 GB to external drive",
    actions: [],
    hints: { category: "transfer.complete" },
    expire_timeout: 7000,
    urgency: 0,
    timestamp: new Date(Date.now() - 1000 * 60 * 180), // 3 hours ago
    host: "server-prod",
  },
  {
    id: 13,
    app_name: "System",
    replaces_id: 0,
    app_icon: "dialog-warning",
    summary: "Low Disk Space",
    body: 'The volume "Home" has only 2.3 GB disk space remaining',
    actions: [],
    hints: { urgency: 2, category: "device" },
    expire_timeout: 0,
    urgency: 2,
    timestamp: new Date(Date.now() - 1000 * 60 * 2), // 2 minutes ago
    host: "workstation-0-1",
  },
]
