name: "Build"

on:
  workflow_run:
    workflows: ["Rust Tests"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build
