name: Rust Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Cache Nix store
        uses: actions/cache@v3
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock', 'flake.nix') }}
          restore-keys: |
            ${{ runner.os }}-nix-
            
      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
            
      - name: Run tests and linting in Nix shell
        run: |
          nix develop --command bash -c "
            # Install cargo-llvm-cov in the Nix environment
            cargo install cargo-llvm-cov
            
            # Generate code coverage
            cargo llvm-cov --all-features --workspace --bins --lcov --output-path lcov.info
            
            # Check formatting
            cargo fmt -- --check
            
            # Run clippy
            cargo clippy --all-targets -- -D warnings
          "
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false
